# The material used to obtain information from a horse.
infoMaterial: FEATHER

# The material that is (temporarily) given to a player to select another horse.
selectorMaterial: FEATHER

# The material used to change the speed while riding a horse.
whipMaterial: BLAZE_ROD

# List of comma-separated values. Each value represents a percentage of the original speed of the horse.
gaits: 0,25,35,50,75,100

# The default gait to use for new horses.
defaultGait: 100

# The gait to reset a horse to when its rider dismounts it.
# Use -1 to not reset the gait and remember the last-used gait instead.
resetGait: -1

# The amount of time (in seconds) you get to select a horse before the process times out.
selectorTimeOut: 60

# The speed penalty (percentage) to give when a horse is exhausted. Use a value of 0 to disable this feature.
exhaustionPenalty: 35

# The amount of time (in seconds) a horse can run at >= 100% speed before getting exhausted.
# This has no effect when exhaustionPenalty is set to <0.
energyDrainTime: 5

# The amount of time (in seconds) it takes for a horse to recover once it is exhausted.
# This has no effect when exhaustionPenalty is set to <0.
energyRecoveryTime: 8

# The number of normal and big smoke particles to repeatedly spawn while a horse is exhausted.
exhaustionSmokeParticles: 4
exhaustionBigSmokeParticles: 1

# Disables the speed buff gained from potions while mounted.
disableMountedSpeedPotionBuff: false

# Whether to use the alternative baby growth method. With the alternative method, baby horses do not grow over time.
# Instead, they will need to be fed by their owner to grow bigger.
# Whether to use the alternative baby growth method. With the alternative method, baby horses/mules/donkeys
# do not grow over time. Instead, they will need to be fed by their owner to grow bigger.
# This option only affects future babies. Currently existing babies are unaffected when changing this option.
alternativeBabyGrowth: true

# The items that can be fed to baby horses/mules/donkeys that use the alternative growth method.
# The format is <Material>:<GrowthPercentage>.
# So "WHEAT:2.5" means that one weed will progress the baby's growth by 2.5 percentage points.
babyFoodGrowthItems:
  - SUGAR:1.5
  - WHEAT:2
  - APPLE:3
  - GOLDEN_CARROT:4
  - GOLDEN_APPLE:10
  - ENCHANTED_GOLDEN_APPLE:15

