# The material used to obtain information from a horse.
infoMaterial: FEATHER

# The material used to change the speed while riding a horse.
whipMaterial: BLAZE_ROD

# List of comma-separated values. Each value represents a percentage of the original speed of the horse.
gaits: 0,25,35,50,75,100

# The default gait to use for new horses.
defaultGait: 100

# The gait to reset a horse to when its rider dismounts it.
# Use -1 to not reset the gait and remember the last-used gait instead.
resetGait: -1

# The names of the genders
nameMale: Stallion
nameFemale: Mare
nameGelding: Gelding

# The speed penalty (percentage) to give when a horse is exhausted. Use a value of 0 to disable this feature.
exhaustionPenalty: 35

# The amount of time (in seconds) a horse can run at >= 100% speed before getting exhausted.
# This has no effect when exhaustionPenalty is set to <0.
energyDrainTime: 5

# The amount of time (in seconds) it takes for a horse to recover once it is exhausted.
# This has no effect when exhaustionPenalty is set to <0.
energyRecoveryTime: 8

# The number of normal and big smoke particles to repeatedly spawn while a horse is exhausted.
exhaustionSmokeParticles: 8
exhaustionBigSmokeParticles: 2

# Disables the speed buff gained from potions while mounted.
disableMountedSpeedPotionBuff: false
