name: Horses
main: nl.pim16aap2.horses.Horses
version: ${project.version}
author: pim16aap2
api-version: 1.17
commands:
  reloadhorses:
    description: Reloads the horses plugin.
    permission: horses.admin.reload
