name: Horses
main: nl.pim16aap2.horses.Horses
version: ${project.version}
author: pim16aap2
api-version: 1.17
commands:
  reloadhorses:
    description: Reloads the horses plugin.
    permission: horses.admin.reload
  edithorse:
    description: Edits an attribute of a horse.
    permission: horses.admin.edit
    usage: /EditHorse <Attribute> [Value]
  gethorseinfo:
    description: Gets the information of a horse.
    permission: horses.user.see_info_menu
    usage: /gethorseinfo <horse UUID>
